version: '3.8'

services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bts
    ports:
      - '5433:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  postgresdb:
